select * from countries;

select * from departments;

select * from employees;

select first_name as 'Fisrt',last_name as 'Last' from employees;

select * from employees
where department_id='60' and salary>6000;

select * from employees
where employee_id = 144;

select * from employees
where salary <(select salary from employees
				where employee_id = 144);
                
select * from employees
where salary =(select max(salary) from employees);

SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
						SELECT DEPARTMENT_ID 
						FROM DEPARTMENTS
						WHERE  DEPARTMENT_NAME = 'MARKETING'
                        );



SELECT SUM(SALARY) AS 'BATON'
FROM EMPLOYEES
WHERE JOB_ID = (
				SELECT JOB_ID
                FROM JOBS
                WHERE JOB_TITLE= 'PROGRAMMER'
				);
                
SELECT COUNT(JOB_ID) 
FROM EMPLOYEES
WHERE JOB_ID LIKE 'IT%';

SELECT SUM(SALARY) AS 'BATON'
FROM EMPLOYEES
WHERE JOB_ID = (
				SELECT JOB_ID
                FROM JOBS
                WHERE JOB_TITLE= 'PROGRAMMER'
				);


SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1
OFFSET 2;

SELECT *
FROM EMPLOYEES
WHERE SALARY =(
				SELECT DISTINCT SALARY
				FROM EMPLOYEES
				ORDER BY SALARY DESC
				LIMIT 1
				OFFSET 2
				);

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY<(
			SELECT MAX(SALARY)
			FROM EMPLOYEES
			);

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (
			SELECT MAX(SALARY)
			FROM EMPLOYEES
			WHERE SALARY <  (
							SELECT MAX(SALARY)
							FROM EMPLOYEES
							)
			);

SELECT MIN(SALARY)
FROM EMPLOYEES
WHERE SALARY > (
			SELECT MIN(SALARY)
			FROM EMPLOYEES
			WHERE SALARY >  (
							SELECT MIN(SALARY)
							FROM EMPLOYEES
							)
			);
            
USE DUMMYDB;
SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS 
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES INNER JOIN DEPARTMENTS 
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES LEFT JOIN DEPARTMENTS 
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES RIGHT JOIN DEPARTMENTS 
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES CROSS JOIN DEPARTMENTS 
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


SELECT *
FROM LOCATIONS;


SELECT m.FIRST_NAME AS 'Employee Name',e.FIRST_NAME AS 'Manager Name'
FROM EMPLOYEES AS m
JOIN EMPLOYEES AS e
ON e.EMPLOYEE_ID = m.MANAGER_ID;

SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
 LEFT JOIN EMPLOYEES
 ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
 WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;
 
 SELECT EMPLOYEES.FIRST_NAME, (AVG_DEPT_SALRY-EMPLOYEES.SALARY) AS 'AVG SALARY'
 FROM EMPLOYEES
	JOIN DEPARTMENTS
    ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
    
    

	