use dummydb;
CREATE TABLE EMPLOYEES(
	FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE,
    DEPARTMENT_ID INT,
    SALARY DECIMAL(10,2)
);

CREATE TABLE DEPARTMENTS(
	DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL
);

SELECT *
	FROM DEPARTMENTSS;


SELECT MAX(SALARY)
	FROM EMPLOYEES
    WHERE SALARY < (
					SELECT MAX(SALARY)
					FROM EMPLOYEES
                    );

SELECT AVG(SALARY), DEPARTMENT_ID 
	FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_NAME,DEPARTMENT_ID
	FROM DEPARTMENTS;

SELECT D.DEPARTMENT_NAME AS "Department Name", AVG(E.SALARY) AS "AVG Salary"
	FROM EMPLOYEES AS E
	JOIN DEPARTMENTS AS D
    ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
    GROUP BY E.DEPARTMENT_ID;


SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
	FROM EMPLOYEES AS E
    INNER JOIN DEPARTMENTS AS D
    ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
	FROM EMPLOYEES AS E
    LEFT JOIN DEPARTMENTS AS D
    ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
	FROM EMPLOYEES AS E
    RIGHT JOIN DEPARTMENTS AS D
    ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT E1.FIRST_NAME, E2.DEPARTMENT_ID
	FROM EMPLOYEES AS E1
	INNER JOIN EMPLOYEES AS E2
	ON E1.DEPARTMENT_ID = E2.DEPARTMENT_ID;
    
SELECT MIN(SALARY)
	FROM EMPLOYEES
    WHERE FIRST_NAME = 'Steven';

SELECT FIRST_NAME AS "Employee name", SALARY
FROM EMPLOYEES
WHERE SALARY < 24000 AND SALARY < 2200;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY < (
				SELECT MIN(SALARY)
				FROM EMPLOYEES
				WHERE FIRST_NAME = 'Steven'
                );

SELECT *
	FROM EMPLOYEES;

SELECT JOB_ID AS "JOB TYPE", COUNT(*) AS TOTAL
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_TITLE AS "JOB TYPE", COUNT(*) AS TOTAL 
	FROM JOBS
    GROUP BY JOB_TITLE;


SELECT D.DEPARTMENT_NAME
	FROM DEPARTMENTS D
	LEFT JOIN EMPLOYEES E 
	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
	WHERE E.DEPARTMENT_ID IS NULL;



